# It is not necessary to specify the symbol '§'!

# Prefix before messages.
# IMPORTANT: Not used in forms.
character: "►"

# Standard message color.
default-color-message: "f"
# Standard text color in the form.
default-color-form: "7"

messages:
  console: "§cThis command must be executed from the server console."
  ingame: "§cThis command must be executed in the game."
  permission: "§cYou don't have enough permissions to execute this command."
  # Format.YELLOW is used.
  usage: "Use: %0"